# Generated by Django 4.0.8 on 2025-04-13 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_student_gpa'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='extracurricular_activities',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='hours_studied',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='performance_index',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='previous_scores',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='sample_question_papers_practiced',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='sleep_hours',
            field=models.DecimalField(blank=True, decimal_places=2, default=8.0, max_digits=4, null=True),
        ),
    ]
